# Generated by Django 5.2 on 2025-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gamme_prix', models.CharField(choices=[('SIM', 'Économique'), ('MOY', 'Modéré'), ('LUX', 'Cher')], default='$', max_length=5)),
                ('type_cuisine', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
