# Generated by Django 5.2 on 2025-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description_courte', models.TextField(blank=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('cout_estime', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes/')),
            ],
        ),
    ]
